# el archivo Values sirve para declarar las variables con valores por defecto y que son utilizadas por las plantillas, los datos son solo de referencia
releaseName: front-finansysweb-modulo-gestion-documental

config: 
  NEXT_PUBLIC_API_BASE_URL: 'https://api-sandbox.bancontinental.com.py/'
  NEXT_PUBLIC_API_BASE_URL: 'http://10.6.3.84:5051/'
  NEXT_PUBLIC_API_TIME_OUT: 60000
  NEXT_PUBLIC_SUSCRIPTION_KEY: 'cc665137fcfb4a95a0c2701e58828e7c'
  NEXT_PUBLIC_CLIENT_SECRET: 'c7cb38ff-abe0-4714-89e2-457eff7c00bf'
  NEXT_PUBLIC_CLIENTE_ID: 'gestion-documental'
  # NEXT_PUBLIC_HOST_VALIDO: 'http://localhost:9000/'
  NEXT_PUBLIC_HOST_VALIDO: 'https://gdi-desa.bancontinental.com.py/'
  NEXT_PUBLIC_URL_REDIRECT: 'https://www.bancontinental.com.py/' 

deployment:  
  replicas: 1

container: 
  registry: localhost:5000
  imagePullPolicy: Always
  version: 0.1.8

ingress:
  tlsSecret: gdi-cer
  host: gdi-desa.bancontinental.com.py
  create: true