# el archivo Values sirve para declarar las variables con valores por defecto y que son utilizadas por las plantillas, los datos son solo de referencia
releaseName: front-finansysweb-modulo-gestion-documental

config: 
  NEXT_PUBLIC_API_BASE_URL: 'https://api-sandbox.bancontinental.com.py/'
  NEXT_PUBLIC_API_BASE_URL: 'https://desa-docker01.bancontinental.com.py:8200'
  NEXT_PUBLIC_API_TIME_OUT: 60000
  NEXT_PUBLIC_SUSCRIPTION_KEY: '578a3e189d3a4da791ad1aa2a00bae3c'
  NEXT_PUBLIC_CLIENT_SECRET: 'c2173556-7eeb-42b7-9150-50c90520a7f6'
  NEXT_PUBLIC_CLIENTE_ID: 'gestion-documental'
  # NEXT_PUBLIC_HOST_VALIDO: 'http://localhost:9000/'
  NEXT_PUBLIC_HOST_VALIDO: 'https://gdi-desa.bancontinental.com.py/'
  NEXT_PUBLIC_URL_REDIRECT: 'https://www.bancontinental.com.py/' 

deployment:  
  replicas: 1

container: 
  registry: localhost:5000
  imagePullPolicy: Always
  version: 0.1.8

ingress:
  tlsSecret: gdi-cer
  host: gdi-desa.bancontinental.com.py
  create: true